development:
  adapter: postgresql
  encoding: unicode
  database: localhost
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1

production
  adapter: postgresql
  encoding: unicode
  database: lallah.db.elephantsql.com
  port: 5432
  pool: 5
  username: ndrcrvue
  password: rxdyBkylzprIa41Nk6_RyGB8Q9FEf8bz


