development:
  adapter: postgresql
  encoding: unicode
  database: localhost
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1

production
  adapter: postgresql
  encoding: unicode
  database: viktor-test.c1hd8r0n5glg.sa-east-1.rds.amazonaws.com
  port: 5432
  pool: 5
  username: postgres
  password: Artur*#06$


